### ISSUE TITLE
Minor display bugs

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/OnlinePlantAtlas#8]
Not sure whether these are recent issues, or of longstanding, but I have noticed two minor things today:

(1) If you reduce the size of the window in Chrome from fullscreen, the BRC logo under the taxon selector on the home page (https://plantatlas2020.org/) blurs. (So, open atlas full screen, press e.g. windows key + right arrow to reduce window to half screen, BRC logo blurs).

(2) If you were previously looking at a species on the site, then the site remembers the species within the taxon selector. If you browse away from the site or close the window and return, the taxon is remembered within the taxon selector on the home page (i.e. https://plantatlas2020.org/), but it cannot actually be selected (you have to delete and retype)

**Comment by burkmarr** [comment]
@sacrevert - I can't reproduce number 1. Can you post a screen grab here?

Re number 2 - why do you want to re-select? If you go to the atlas page, isn't the correct map already shown for the taxon on summary tab (and correct info for all of the tabs)? (It should be.)

**Comment by sacrevert** [comment]
For 1:
![image](https://user-images.githubusercontent.com/5985134/224776257-2c0d84f9-e8a1-495a-b1f0-d2f7ecebff86.png)

**Comment by sacrevert** [comment]
For (2), yes, you are correct, but it seems odd to me that neither clicking nor pressing enter on the selected taxon in the selector actually takes you to the Atlas page in this instance (as it would if you had newly chosen the taxon)

**Comment by burkmarr** [comment]
Re 2) I think it's because no 'change event' is fired - that's what the code will be triggered by.
Re 1) - that's really odd. I don't see anything like that with Chrome and, if it were a general problem, you'd expect it to affect the other logo images too. Can you clear your cache and then see if you can reproduce the problem with the same workflow?

**Comment by sacrevert** [comment]
Re (2) is it possible to change at some point (not urgent), just find it odd that a positive user action yields no result here (ofc, if it's a massive hassle, then I'm sure we can live with it)
Re (1) did control + shift + R and still happening, is that what you meant? or do i need to clear cache in Chrome via Settings?

**Comment by burkmarr** [comment]
Re 2 - okay lets leave open and I'll see if it can be addressed at some point.
Re 1 - yes that is what I meant and I'm really surprised it didn't fix it. Since I can't reproduce, we'll have to put this on the back-burner for the moment. If you get a chance to try on anyone else's computer - let me know the results. 

If anyone else reading this can try to reproduce this problem on their computer with Chrome (see steps below), please add a comment to let us know the result.

- Open atlas full screen.
- Reduce browser size, e.g. press windows key + right arrow to reduce window to half screen.
- Is the BRC logo blurred (see image in https://github.com/BiologicalRecordsCentre/OnlinePlantAtlas/issues/8#issuecomment-1466568636)

**Comment by japonicus** [comment]
Hi Oli,

Thanks, I'll put together a fix for (2) tomorrow. The change event
behaviour needs to be different on the homepage picker than on the species
pages (on the homepage, 'change' should fire every time).

regards,

Tom

**Comment by japonicus** [comment]
I've updated the [taxonpicker](https://github.com/BSBI/Taxonpicker), adding an 'alwaysFireChangeEvent' instance property to TaxonPickerField.

This should be set to TRUE for taxon pickers used on non-species pages, where any picker selection should lead to page navigation, even if the selection hasn't changed.

**Comment by japonicus** [comment]
I can reproduce the BRC logo issue, but not consistently and not when hardware assisted rendering is turned off in Chrome. I can't find anything wrong with the image (it passes pngcheck without any errors), so I don't think this is fixable at our end - it's an obscure browser bug. Perhaps we should file a Chromium bug sometime, if a test page can be put together.

Is the BRC logo that we're using the current one, as [BRC's homepage](https://www.brc.ac.uk/) has a slightly different version with a green circle, more like UKCEH's logo.

Thanks for fixing the taxon picker (and all the other changes today).

**Comment by sacrevert** [comment]
Thanks both. I think we should stick with the current logos, as the joint BRC/UKCEH one on the BRC homepage is not going to fit nicely below the others below the taxon selector. I'll leave any Chrome bug reports to @burkmarr -- entirely up to you! Please close if you don't have time to worry about Chrome bugs

**Comment by burkmarr** [comment]
Moved issue to code repo: https://github.com/BiologicalRecordsCentre/bsbi-atlas-drupal8/issues/1
